### ISSUE TITLE
ResinCLI - Ensure resin sync works

### ISSUE THREAD

**Issue by lifeeth** [resin-io/autohat#30]
Ensure the working of -> http://docs.resin.io/tools/cli/#sync-uuid-
1. Adapt ondevice repo to work with resin sync
2. Edit server.py in https://github.com/resin-io/autohat-ondevice/blob/master/server.py
   to return "Hello Resin Sync!" when accessed over device URL.
3. The sync process should start with status messages appearing on each step ('Stopping application container...', 'Syncing..', 'Starting application container...').
4. At the end of resin sync a "resin sync completed successfully!" message should appear.
5. The device's Public Device URL should now show the new message, e.g. 'Hello Resin Sync!'

**Comment by horia-delicoti** [comment]
Connects to https://github.com/resin-io/resin-proxy/issues/43
