### ISSUE TITLE
Resin Supervisor - Provisioning a device on an app that already has deltas pushed

### ISSUE THREAD

**Issue by lifeeth** [resin-io/autohat#32]
Test Steps:

Provision a device on an app that already has the RESIN_SUPERVISOR_DELTA=1 var and a pushed image.

Expected result:
1. The device should appear on the dashboard and correctly download the image for the app. 
2. The devices env variables should show RESIN_SUPERVISOR_DELTA env var set to 1.

**Comment by pcarranzav** [comment]
Recent change since we now don't expose config vars: the device env vars will not show the RESIN_SUPERVISOR_DELTA inside the container.
