### ISSUE TITLE
Install a specific version of the CLI so we have control over the introduction of breaking changes

### ISSUE THREAD

**Issue by Page-** [resin-io/autohat#5]
The CLI can introduce breaking changes which could make the tests fail until they are rewritten.  If we use a fixed version of the CLI instead then we can know the tests will continue to work whilst we upgrade them to the new version.

**Comment by villaseca** [comment]
Is it okay by fixing it @4.2.0?

**Comment by Page-** [comment]
Yep, although you could also use `@^4.2.0` in order to automatically pick up minor/patch changes (which are non-breaking)
